/**
 * Bolded entries from the DS Compendium's "Glossary Index" section
 * (Rules/Chapters/Introduction.md), used to seed the term index on first
 * load. Users add or remove terms afterward via the plugin's settings.
 */
export const DEFAULT_TERMS: string[] = [
	"Ability",
	"Ability Roll",
	"Adjacent",
	"Advance Move Action",
	"Agility",
	"Aid Attack Maneuver",
	"Ally",
	"Ancestry",
	"Area of Effect",
	"Argument",
	"Artifact",
	"Artisan",
	"Aura",
	"Background",
	"Bane",
	"Bleeding",
	"Bonus",
	"Breakthrough",
	"Burrow",
	"Burst",
	"Capital",
	"Career",
	"Catch Breath Maneuver",
	"Censor",
	"Characteristics",
	"Charge Main Action",
	"Ceiling",
	"Clarity",
	"Class",
	"Claw Dirt",
	"Climb",
	"Combat Round",
	"Complication",
	"Concealment",
	"Condition",
	"Conduit",
	"Consequence",
	"Consumable",
	"Cover",
	"Crafting Project",
	"Crawl",
	"Creature",
	"Critical Hit",
	"Cube",
	"Culture",
	"d3",
	"d6",
	"d10",
	"d100",
	"Damage",
	"Damage Immunity",
	"Damage Type",
	"Damage Weakness",
	"Damaging Terrain",
	"Dazed",
	"Defend Main Action",
	"Devil",
	"Difficult Terrain",
	"Dig Maneuver",
	"Director",
	"Discipline",
	"Disengage Move Action",
	"Distance",
	"Double Bane",
	"Double Edge",
	"Downtime Project",
	"Dragon Knight",
	"Drama",
	"Dwarf",
	"Dying",
	"Echelon",
	"Edge",
	"Elementalist",
	"EoT",
	"Enemy",
	"Enhancement",
	"Escape Grab Maneuver",
	"Essence",
	"Experience",
	"Falling",
	"Ferocity",
	"Flanking",
	"Fly",
	"Focus",
	"Forced Movement",
	"Follower",
	"Free Maneuver",
	"Free Strike",
	"Free Triggered Action",
	"Frightened",
	"Fury",
	"God",
	"Grab Maneuver",
	"Grabbed",
	"Ground",
	"Group Test",
	"Guide",
	"Hakaan",
	"Heal Main Action",
	"Hero",
	"Heroic Ability",
	"Hero Tokens",
	"Heroic Resource",
	"Hide Maneuver",
	"High Elves",
	"High Ground",
	"Hover",
	"Human",
	"Humanoid",
	"Implement",
	"Insight",
	"Interest",
	"Intuition",
	"Item Prerequisite",
	"Jump",
	"Kit",
	"Knockback Maneuver",
	"Level",
	"Leveled Treasure",
	"Line",
	"Line of Effect",
	"Main Action",
	"Malice",
	"Maneuver",
	"Manifold",
	"Melee",
	"Melee Free Strike",
	"Memonek",
	"Might",
	"Montage Test",
	"Motivation",
	"Mounted Combat",
	"Move Action",
	"Movement",
	"Mundane",
	"Natural 19 or 20",
	"Natural Roll",
	"Negotiation",
	"No Action",
	"NPC",
	"Null",
	"Object",
	"Objective",
	"Opportunity Attack",
	"Opposed Power Roll",
	"Orc",
	"Orden",
	"Patience",
	"Penalty",
	"Perk",
	"Piety",
	"Pitfall",
	"Polder",
	"Potency",
	"Power Roll",
	"Presence",
	"Project Event",
	"Project Goal",
	"Project Points",
	"Project Roll",
	"Project Source",
	"Prone",
	"Pull",
	"Push",
	"Ranged",
	"Ranged Free Strike",
	"Reactive Test",
	"Reason",
	"Recoveries",
	"Recovery Value",
	"Renown",
	"Research Project",
	"Respite",
	"Respite Activity",
	"Restrained",
	"Retainer",
	"Revenant",
	"Reward",
	"Ride Move Action",
	"Rolled Damage",
	"Sage",
	"Saint",
	"Save Ends",
	"Saving Throw",
	"Search for Hidden Creatures Maneuver",
	"Shadow",
	"Shift",
	"Side",
	"Signature Ability",
	"Size",
	"Skill",
	"Slide",
	"Slowed",
	"Space",
	"Speed",
	"Square",
	"Stability",
	"Stamina",
	"Stand Up Maneuver",
	"Strained",
	"Strike",
	"Subclass",
	"Suffocating",
	"Supernatural",
	"Surge",
	"Surprised",
	"Swim",
	"Tactician",
	"Talent",
	"Taunted",
	"Target",
	"Teleport",
	"Temporary Stamina",
	"Test",
	"Tier Outcome",
	"Tier 1",
	"Tier 2",
	"Tier 3",
	"Title",
	"Time Raider",
	"Timescape",
	"Treasure",
	"Triggered Action",
	"Trinket",
	"Troubadour",
	"Turn",
	"Unattended Object",
	"Underwater combat",
	"Untyped Damage",
	"Vasloria",
	"Vertical",
	"Victories",
	"Walk",
	"Wall",
	"Weakened",
	"Wealth",
	"Winded",
	"Wode Elf",
	"Wrath",
];

/**
 * Default terms with an explicit target instead of a name-matched heading —
 * either because the desired term text differs from the glossary heading's
 * own title (e.g. "Charge" for the "Charge Main Action" heading), or
 * because the target isn't in the glossary at all (a Compendium chapter's
 * own heading). Merged directly into the resolved term set on every
 * rebuild, same as DEFAULT_TERMS but skipping the by-name heading lookup.
 */
export const DEFAULT_TERM_TARGETS: Record<string, string> = {
	Charge: "ds-glossary#Charge Main Action",
	Surges: "DS Compendium/Rules/Chapters/Classes#Surges",
	Disengage: "ds-glossary#Disengage Move Action",
};
